/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;
import VistaLibros.*;
import Biblioteca.*;

/**
 *
 * @author juanc
 */
public class Usuario_Principal extends javax.swing.JFrame {

    AdminLibro adminLibro;

    /**
     * Creates new form Usuario_Principal
     */
    public Usuario_Principal() {
        initComponents();
        this.adminLibro = new AdminLibro();
        adminLibro.generarLibros();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLibro4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblLibro1 = new javax.swing.JLabel();
        lblLibro2 = new javax.swing.JLabel();
        lblLibro3 = new javax.swing.JLabel();
        lblLibro5 = new javax.swing.JLabel();
        btnLibro8 = new javax.swing.JButton();
        btnLibro2 = new javax.swing.JButton();
        btnLibro3 = new javax.swing.JButton();
        btnLibro4 = new javax.swing.JButton();
        lblLibro6 = new javax.swing.JLabel();
        lblLibro7 = new javax.swing.JLabel();
        lblLibro8 = new javax.swing.JLabel();
        btnLibro1 = new javax.swing.JButton();
        btnLibro5 = new javax.swing.JButton();
        btnLibro6 = new javax.swing.JButton();
        btnLibro7 = new javax.swing.JButton();
        lblLibro10 = new javax.swing.JLabel();

        lblLibro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/libro1.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setText("volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido señor/a: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIBLIOTECA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtUsername.setEditable(false);
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 110, -1));
        jPanel1.add(lblLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 150));
        jPanel1.add(lblLibro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, 150));
        jPanel1.add(lblLibro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, 150));
        jPanel1.add(lblLibro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 90, 150));

        btnLibro8.setText("ver");
        btnLibro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        btnLibro2.setText("ver");
        btnLibro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        btnLibro3.setText("ver");
        btnLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        btnLibro4.setText("ver");
        btnLibro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));
        jPanel1.add(lblLibro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 150));
        jPanel1.add(lblLibro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 90, 150));
        jPanel1.add(lblLibro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 90, 150));

        btnLibro1.setText("ver");
        btnLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btnLibro5.setText("ver");
        btnLibro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        btnLibro6.setText("ver");
        btnLibro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        btnLibro7.setText("ver");
        btnLibro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));
        jPanel1.add(lblLibro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 90, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Principal aux = new Principal();
        aux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    public void crearIconos() {
        Icon mIcon = new ImageIcon(new ImageIcon(getClass().getResource("/images/libro1.jpg")).getImage()
                .getScaledInstance(lblLibro1.getWidth(), lblLibro1.getHeight(), 0));

        Icon mIcon2 = new ImageIcon(new ImageIcon(getClass().getResource("/images/libro2.jpg")).getImage()
                .getScaledInstance(lblLibro2.getWidth(), lblLibro2.getHeight(), 0));

        Icon mIcon3 = new ImageIcon(new ImageIcon(getClass().getResource("/images/libro3.png")).getImage()
                .getScaledInstance(lblLibro3.getWidth(), lblLibro3.getHeight(), 0));

        Icon mIcon4 = new ImageIcon(new ImageIcon(getClass().getResource("/images/libro4.png")).getImage()
                .getScaledInstance(lblLibro5.getWidth(), lblLibro5.getHeight(), 0));

        Icon mIcon5 = new ImageIcon(new ImageIcon(getClass().getResource("/images/libro5.jpeg")).getImage()
                .getScaledInstance(lblLibro6.getWidth(), lblLibro6.getHeight(), 0));

        Icon mIcon6 = new ImageIcon(new ImageIcon(getClass().getResource("/images/libro6.gif")).getImage()
                .getScaledInstance(lblLibro7.getWidth(), lblLibro7.getHeight(), 0));

        Icon mIcon7 = new ImageIcon(new ImageIcon(getClass().getResource("/images/libro7.jpeg")).getImage()
                .getScaledInstance(lblLibro8.getWidth(), lblLibro8.getHeight(), 0));

        Icon mIcon8 = new ImageIcon(new ImageIcon(getClass().getResource("/images/libro8.gif")).getImage()
                .getScaledInstance(lblLibro10.getWidth(), lblLibro10.getHeight(), 0));

        lblLibro1.setIcon(mIcon);
        lblLibro2.setIcon(mIcon2);
        lblLibro3.setIcon(mIcon3);
        lblLibro5.setIcon(mIcon5);
        lblLibro6.setIcon(mIcon6);
        lblLibro7.setIcon(mIcon7);
        lblLibro8.setIcon(mIcon8);
        lblLibro10.setIcon(mIcon4);
    }

    private void btnLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro1ActionPerformed
        // TODO add your handling code here:
        Libro1 aux = new Libro1(adminLibro);
        aux.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLibro1ActionPerformed

    private void btnLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro2ActionPerformed
        // TODO add your handling code here:
        Libro2 aux = new Libro2(adminLibro);
        aux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLibro2ActionPerformed

    private void btnLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro3ActionPerformed
        // TODO add your handling code here:
        Libro3 aux = new Libro3(adminLibro);
        aux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLibro3ActionPerformed

    private void btnLibro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro4ActionPerformed
        // TODO add your handling code here:        
        Libro4 aux = new Libro4(adminLibro);
        aux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLibro4ActionPerformed

    private void btnLibro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro5ActionPerformed
        // TODO add your handling code here:        
        Libro5 aux = new Libro5(adminLibro);
        aux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLibro5ActionPerformed

    private void btnLibro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro6ActionPerformed
        // TODO add your handling code here:        
        Libro6 aux = new Libro6(adminLibro);
        aux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLibro6ActionPerformed

    private void btnLibro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro7ActionPerformed
        // TODO add your handling code here:        
        Libro7 aux = new Libro7(adminLibro);
        aux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLibro7ActionPerformed

    private void btnLibro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro8ActionPerformed
        // TODO add your handling code here:        
        Libro8 aux = new Libro8(adminLibro);
        aux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLibro8ActionPerformed

    public void setTextUser(String user) {
        txtUsername.setText(user);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLibro1;
    private javax.swing.JButton btnLibro2;
    private javax.swing.JButton btnLibro3;
    private javax.swing.JButton btnLibro4;
    private javax.swing.JButton btnLibro5;
    private javax.swing.JButton btnLibro6;
    private javax.swing.JButton btnLibro7;
    private javax.swing.JButton btnLibro8;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLibro1;
    private javax.swing.JLabel lblLibro10;
    private javax.swing.JLabel lblLibro2;
    private javax.swing.JLabel lblLibro3;
    private javax.swing.JLabel lblLibro4;
    private javax.swing.JLabel lblLibro5;
    private javax.swing.JLabel lblLibro6;
    private javax.swing.JLabel lblLibro7;
    private javax.swing.JLabel lblLibro8;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
